services:
  robinhood-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: robinhood-ai-trading-bot:latest
    container_name: robinhood-ai-trading-bot
    environment:
      AUTO_MODE_CONFIRM: "no"
    volumes:
      - ./config.py:/app/config.py:ro
      - ./.tokens:/root/.tokens
    stdin_open: true
    tty: true
